### ISSUE TITLE
apm_environment not working

### ISSUE THREAD

**Issue by michbeck100** [matthyx/kong-elastic-apm#17]
If I set the config value for `apm_environment` I would expect that I can switch between environments in Kibana. 

But setting this config doesn't change anything. I tried with the version in your docker-compose setup and also with ELK 8.3. But for both setups it didn't work.

Can you tell why it's not working? Is it working on your side?

**Comment by michbeck100** [comment]
Here's my `kong.yaml`:

```yaml
plugins:
  - name: elastic-apm
    enabled: true
    service: hello
    config:
      apm_active: true
      apm_server_url: http://apm-server:8200
      apm_service_name: Kong
      apm_environment: DEV
      apm_log_file: stdout
      apm_log_level: debug
      apm_global_labels: label=test
```

BTW: `apm_global_labels` didn't work either.
